Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: nivas
Traceback (most recent call last):
  File "C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py", line 4, in <module>
    if b == isdigit and a == isalpha:
NameError: name 'isdigit' is not defined

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: nivas
Hello nivas

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 22
Enter the Name: 23
Hello 23

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: 1
Hello 1

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: 22
Hello 22

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: 1
Please Enter the VALID INFO.!!

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: 22
Please Enter the VALID INFO.!!

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: 1
Please Enter the VALID INFO.!!
Enter the AGE: 1
2
2

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 1
Enter the Name: 1
Please Enter the VALID INFO.!!
Enter the AGE: 1
Please Enter the VALID INFO.!!
Enter the AGE: 2
Please Enter the VALID INFO.!!
Enter the AGE: 22
Please Enter the VALID INFO.!!
Enter the AGE: 
= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: nnivas
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12h
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
nHello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
bHello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12
Hello 'nnivas' and Your AGE is: 12

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 1
Enter the Name: 1
Please Enter the VALID INFO.!!

= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 12
Enter the Name: Nivas
Hello 'Nivas' and Your AGE is: 12
Enter the City: kakinada
Enter the State: AP
Hello 'Nivas' and Your AGE is: 12
Enter the City: 
= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 22
Enter the Name: nivas
Hello 'nivas' and Your AGE is: 22
Enter the City: kakinada
Enter the State: ap
Please Enter the VALID INFO.!!
Enter the AGE: 
= RESTART: C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py
Enter the AGE: 22
Enter the Name: nivas
Hello 'nivas' and Your AGE is: 22
Enter the City: kakinada
Enter the State: ap
Traceback (most recent call last):
  File "C:/Users/balam/Desktop/python-course-work/Day-9/Day-9 - Conditions.py", line 8, in <module>
    if x.isalpha() and y.isaplha():
AttributeError: 'str' object has no attribute 'isaplha'. Did you mean: 'isalpha'?
